--CREATE DATABASE ONE
CREATE DATABASE DBASE1
USE DBASE1;
--CREATE ONE TABLE.
CREATE TABLE TB1(ID INT PRIMARY KEY IDENTITY, NAME VARCHAR(20), AGE INT, EMAIL VARCHAR(MAX))
INSERT INTO TB1 VALUES 
('AJAY KUMAR',22,'ajay123@gmail.com' ),
('SUMIT KUMAR',23,'sumit123@gmail.com' ),
('VIRAT KUMAR',22,'virat123@gmail.com' );
SELECT * FROM TB1;

--CREATE DATABASE TWO
CREATE DATABASE DBASE2;
USE DBASE2;
SELECT * INTO DBASE2.DBO.TB2  FROM DBASE1.DBO.TB1;
SELECT * FROM TB2;